ubihome:
  name: UbiHome Example

bme280:

sensor:
  - platform: bme280
    update_interval: 30s
    name: 'Temperature'

# Native Homeassistant API
api:
  # encryption:
  #   key:  # Generate here: https://ubihome.github.io/features/connectivity/native_api.html
