name: docs
on:
  pull_request:
    paths:
      - documentation/**
      - .dagger/**
      - dagger.json
      - .github/workflows/docs.yml
    branches-ignore:
      - release
  push:
    branches:
      - main
    paths:
      - documentation/**
      - .dagger/**
      - dagger.json
      - .github/workflows/docs.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run docs checks
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: v0.20.8
          call: docs-check
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build docs site with Dagger
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: v0.20.8
          call: docs-build-dir export --path=./documentation/site
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Deploy to ubihome.github.io repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: UbiHome/ubihome.github.io
          publish_dir: ./documentation/site
          publish_branch: gh-pages
          personal_token: ${{ secrets.CUSTOM_GITHUB_PAT }}
