name: Release

on:
  push:
    # Just for debugging
    # branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.target }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            file: ubihome
            release_file_name: ubihome-linux-x86_64

          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            file: ubihome.exe
            release_file_name: ubihome-windows-x86_64.exe

          - runs-on: macos-26-intel
            target: x86_64-apple-darwin
            file: ubihome
            release_file_name: ubihome-macos-x86_64

          - runs-on: macos-26
            target: aarch64-apple-darwin
            file: ubihome
            release_file_name: ubihome-macos-aarch64

          - runs-on: ubuntu-24.04
            target: armv7-unknown-linux-musleabi
            file: ubihome
            release_file_name: ubihome-linux-armv7

          - runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabi
            file: ubihome
            release_file_name: ubihome-linux-arm

          # - runs-on: ubuntu-24.04
          #   target: aarch64-unknown-linux-musl

          # - runs-on: ubuntu-24.04
          #   target: riscv64gc-unknown-linux-gnu

          # - runs-on: ubuntu-24.04
          #   target: x86_64-unknown-freebsd

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add extra packages (MacOS)
        if: startsWith(matrix.runs-on, 'macos-')
        run: brew install libmodbus

      - name: Add extra packages (Linux)
        if: matrix.runs-on == 'ubuntu-24.04'
        run: sudo apt install -y libdbus-1-dev pkg-config libasound2-dev

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          # Add "--locked" again when release please is not updating all Cargo.toml files
          args: '--release'
          strip: true

      - name: Copy example config (Linux)
        if: matrix.runs-on == 'ubuntu-24.04'
        run: cp documentation/docs/getting_started/linux.yml config.yaml

      - name: Copy example config (Windows)
        if: startsWith(matrix.runs-on, 'windows-')
        run: cp documentation/docs/getting_started/windows.yml config.yaml

      - name: Copy example config (macOS)
        if: startsWith(matrix.runs-on, 'macos-')
        run: cp documentation/docs/getting_started/macos.yml config.yaml

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubihome
          target: ${{ matrix.target }}
          changes-file: null
          extra-files: |
            README.md
            config.yaml

      - name: Rename Binary
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.file }} target/${{ matrix.target }}/release/${{ matrix.release_file_name }}

      # Upload binaries directly (for auto update)
      - name: Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.release_file_name }}
